### ISSUE TITLE
Web: Fail when building storybook 

### ISSUE THREAD

**Issue by gialynguyen** [VC-Team/yemusic#40]
Fail when building Storybook
```
(0 , react_jsx_dev_runtime__WEBPACK_IMPORTED_MODULE_1__.jsxDEV) is not a function
TypeError: (0 , react_jsx_dev_runtime__WEBPACK_IMPORTED_MODULE_1__.jsxDEV) is not a function
    at Object.Template (http://localhost:3000/main.c36f1d9f.iframe.bundle.js:1:21387)
    at undecoratedStoryFn (http://localhost:3000/759.d1ae0dfb.iframe.bundle.js:2:343582)
    at http://localhost:3000/759.d1ae0dfb.iframe.bundle.js:2:267632
    at http://localhost:3000/759.d1ae0dfb.iframe.bundle.js:2:335649
    at jsxDecorator (http://localhost:3000/759.d1ae0dfb.iframe.bundle.js:2:208550)
    at http://localhost:3000/759.d1ae0dfb.iframe.bundle.js:2:267632
    at http://localhost:3000/759.d1ae0dfb.iframe.bundle.js:2:335904
    at http://localhost:3000/759.d1ae0dfb.iframe.bundle.js:2:335649
    at http://localhost:3000/759.d1ae0dfb.iframe.bundle.js:2:15291
    at withActions.name (http://localhost:3000/759.d1ae0dfb.iframe.bundle.js:2:15475)
```
<img width="2551" alt="image" src="https://user-images.githubusercontent.com/29276005/160427407-1de43a93-1df7-487d-a63c-0e4b6b1a311b.png">

**ref:** https://github.com/nrwl/nx/issues/8403

**Comment by gialynguyen** [comment]
https://github.com/nrwl/nx/releases/tag/13.9.4
Upgrade NX 13.9.4 to resolve

**Comment by thaihoanganh** [comment]
I run and checked `storybook` in my local, it works with no problem. Maybe I need to upgrade dependencies
